### ISSUE TITLE
VPA can not get argocds/scale

### ISSUE THREAD

**Issue by cchen666** [openshift/vertical-pod-autoscaler-operator#124]
How to reproduce:

1. Install Red Hat Gitops Operator
2. Create such VPA CR:

```
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: test-vpa-gitops
  namespace: openshift-gitops
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: StatefulSet
    name: openshift-gitops-application-controller
  updatePolicy:
    updateMode: "Off"
```

3. Check VPA status:

```
status:
  conditions:
    - lastTransitionTime: '2022-05-04T01:52:10Z'
      message: >-
        Error checking if target is a topmost well-known or scalable controller:
        Unhandled targetRef [argoproj.io/v1alpha1](https://argoproj.io/v1alpha1) / ArgoCD / openshift-gitops,
        last error [argocds.argoproj.io](https://argocds.argoproj.io/) "openshift-gitops" is forbidden: User
        "system:serviceaccount:openshift-vertical-pod-autoscaler:vpa-recommender"
        cannot get resource "argocds/scale" in API group "[argoproj.io](https://argoproj.io/)" in the
        namespace "openshift-gitops"
      status: 'True'
      type: ConfigUnsupported
```
